#!/bin/bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

PROJECT="${1:?Usage: chain-create.sh <project_name>}"
CHAIN_DIR="claude-chain/$PROJECT"

if [ -d "$CHAIN_DIR" ]; then
    echo "Error: Project directory already exists: $CHAIN_DIR"
    exit 1
fi

echo "Creating new Claude Chain project: $PROJECT"
echo ""

# Gather configuration
read -p "Base branch [main]: " BASE_BRANCH
BASE_BRANCH="${BASE_BRANCH:-main}"

read -p "Assignee [gestrich]: " ASSIGNEE
ASSIGNEE="${ASSIGNEE:-gestrich}"

read -p "Labels (comma-separated, in addition to 'claudechain') []: " LABELS

read -p "Create a custom PR template? (y/N) " CREATE_PR_TEMPLATE

# Create directory
mkdir -p "$CHAIN_DIR"

# Write configuration.yml
cat > "$CHAIN_DIR/configuration.yml" <<EOF
assignee: $ASSIGNEE
baseBranch: $BASE_BRANCH
EOF

if [ -n "$LABELS" ]; then
    echo "labels: $LABELS" >> "$CHAIN_DIR/configuration.yml"
fi

echo "Created $CHAIN_DIR/configuration.yml"

# Write spec.md template
cat > "$CHAIN_DIR/spec.md" <<'EOF'
# Project Title

Description of what this chain accomplishes.

## Instructions

Instructions for Claude to follow on each task.

## Tasks

- [ ] First task
- [ ] Second task
EOF

echo "Created $CHAIN_DIR/spec.md (edit this with your tasks)"

# Write pr-template.md if requested
if [[ "$CREATE_PR_TEMPLATE" =~ ^[Yy]$ ]]; then
    cat > "$CHAIN_DIR/pr-template.md" <<'EOF'
## Details

{{TASK_DESCRIPTION}}

This PR was generated by [ClaudeChain](https://github.com/gestrich/AIDevTools).

## Testing notes
QA not needed - no functional impact; safe if build passes.
EOF
    echo "Created $CHAIN_DIR/pr-template.md"
fi

echo ""
echo "Chain project created at $CHAIN_DIR"
echo ""
echo "Next steps:"
echo "  1. Edit $CHAIN_DIR/spec.md with your task list"
echo "  2. Optionally add pre-action.sh / post-action.sh"
echo "  3. Commit and push to '$BASE_BRANCH'"
echo "  4. Trigger with: $SCRIPT_DIR/chain-trigger.sh $PROJECT $BASE_BRANCH"
